// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALkIPslPX8ugZXdgbNke-4KocQl0mcZ2s',
    appId: '1:460195914488:web:16b514c702264cd6cd910d',
    messagingSenderId: '460195914488',
    projectId: 'slowpizza-e4bc3',
    authDomain: 'slowpizza-e4bc3.firebaseapp.com',
    storageBucket: 'slowpizza-e4bc3.firebasestorage.app',
    measurementId: 'G-S3CWBVBTSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSxHFlhnhLW_bxGobOiseXoROr5QErvo',
    appId: '1:460195914488:android:699020e201e810d0cd910d',
    messagingSenderId: '460195914488',
    projectId: 'slowpizza-e4bc3',
    storageBucket: 'slowpizza-e4bc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHirSztVYbDBn3bdv7Y8jsQAw6dPLfEoM',
    appId: '1:460195914488:ios:fc6b1ee649af0267cd910d',
    messagingSenderId: '460195914488',
    projectId: 'slowpizza-e4bc3',
    storageBucket: 'slowpizza-e4bc3.firebasestorage.app',
    iosBundleId: 'com.example.slowpizzaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHirSztVYbDBn3bdv7Y8jsQAw6dPLfEoM',
    appId: '1:460195914488:ios:fc6b1ee649af0267cd910d',
    messagingSenderId: '460195914488',
    projectId: 'slowpizza-e4bc3',
    storageBucket: 'slowpizza-e4bc3.firebasestorage.app',
    iosBundleId: 'com.example.slowpizzaWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALkIPslPX8ugZXdgbNke-4KocQl0mcZ2s',
    appId: '1:460195914488:web:1f4fc88e076992a9cd910d',
    messagingSenderId: '460195914488',
    projectId: 'slowpizza-e4bc3',
    authDomain: 'slowpizza-e4bc3.firebaseapp.com',
    storageBucket: 'slowpizza-e4bc3.firebasestorage.app',
    measurementId: 'G-QZJ3XKQ0N1',
  );
}
